### ISSUE TITLE
Distribution name for WMF packages

### ISSUE THREAD

**Issue by ottomata** [wikimedia-incubator/debianize#3]
Sooo, according to the wikitech documenation, packages we build need to be built for specific distributions with specific distribution names:

> For distribution, use the distribution that the package has been compiled for, and under. Usually, any given compiled package should be for one distribution only, e.g. hardy-wikimedia OR lucid-wikimedia. This should match the field in the package's Changelog. Only in special circumstances a given package can be used under multiple distribution versions, .e.g. if the package contains only scripts (no binaries).

So, distribution names should be things like "lucid-wikimedia" and "precise-wikimedia".  The actual package that gets built should also be named accordingly.  When changelogs are generated, the first line of the change should read something like

> udp-filter (0.2.6-1~lucid) lucid-wikimedia; urgency=low

or

> udp-filter (0.2.6-1~precise) precise-wikimedia; urgency=low

depending on the Ubuntu distro being built for.

**Comment by wsdookadr** [comment]
Fixed in these [two](https://github.com/wikimedia-incubator/debianize/commit/8d7cff2c93fb79a8deb19ae75624190b40b6ad49)  [commits](https://github.com/wikimedia-incubator/debianize/commit/21346e779af4a80dbb8d090a0e58d8ccddd24e92)
